'use strict';
'require view';
'require fs';
'require ui';
const HELPER='/usr/libexec/mrouter-setup';
function tx(v){return [String(v==null||v===''?'—':v)];}
function exec(a){return fs.exec(HELPER,a||[]).catch(function(e){return{code:1,stdout:'',stderr:String(e)};});}
function parse(r){let s={done:false,pending:false,lanDev:'',wanDev:'',lanIP:'',backup:'',mode:'',devs:[]};String((r&&r.stdout)||'').split(/\r?\n/).forEach(function(l){let p=l.split('|');if(p[0]==='STATUS'){s.done=p[1]==='1';s.pending=p[2]==='1';s.lanDev=p[3]||'';s.wanDev=p[4]||'';s.lanIP=p[5]||'';s.backup=p[6]||'';s.mode=p[7]||'';}else if(p[0]==='DEV')s.devs.push({name:p[1],mac:p[2]});});return s;}
function notice(m,t){ui.addNotification(null,E('p',{},tx(m)),t||'info');}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,load:function(){return exec(['status']);},render:function(raw){
 let st=parse(raw),wan=E('select',{'class':'m-ios-input'}),lan=E('select',{'class':'m-ios-input'});st.devs.forEach(function(d){wan.appendChild(E('option',{'value':d.name},tx(d.name+' · '+d.mac)));lan.appendChild(E('option',{'value':d.name},tx(d.name+' · '+d.mac)));});if(st.wanDev)wan.value=st.wanDev;if(st.lanDev)lan.value=st.lanDev;
 let ip=E('input',{'class':'m-ios-input','type':'text','value':st.lanIP||'192.168.8.1'}),iot=E('input',{'type':'checkbox'});
 let keep=E('button',{'type':'button','class':'m-secondary-button'},tx(st.done&&st.mode==='keep'?'Existing network preserved':'Keep Current OpenWrt Network'));if(st.done&&st.mode==='keep')keep.disabled=true;keep.addEventListener('click',function(){keep.disabled=true;exec(['keep']).then(function(r){if(r.code){keep.disabled=false;notice(r.stderr||'Could not save setup state.','error');}else window.location.reload();});});
 let apply=E('button',{'type':'button','class':'m-ios-button'},tx('Save 2-Port Profile'));apply.addEventListener('click',function(){if(wan.value===lan.value){notice('WAN and LAN must use different devices.','error');return;}if(!window.confirm('Save this WAN/LAN configuration? Mrouter will create a backup first. The running network is not restarted automatically.'))return;apply.disabled=true;exec(['twoport',wan.value,lan.value,ip.value.trim(),iot.checked?'1':'0']).then(function(r){if(r.code){apply.disabled=false;notice(r.stderr||'Could not save network profile.','error');}else window.setTimeout(function(){window.location.reload();},700);});});
 let rollback=E('button',{'type':'button','class':'m-danger-button'},tx(st.backup?'Restore Last Setup Backup':'No Setup Backup'));rollback.disabled=!st.backup;rollback.addEventListener('click',function(){if(!window.confirm('Restore the latest Mrouter setup backup? A reboot will still be required.'))return;rollback.disabled=true;exec(['rollback']).then(function(r){if(r.code){rollback.disabled=false;notice(r.stderr||'No backup could be restored.','error');}else window.location.reload();});});
 let profile=E('div',{'class':'m-section'},[E('h3',{},tx('Optional 2-Port Router Profile')),E('p',{'class':'m-muted'},tx('For a fresh appliance or VM. Choose the ports explicitly. Mrouter creates a backup before writing the profile and does not restart networking automatically.')),E('div',{'class':'m-service-form'},[E('label',{},[E('span',{},tx('WAN device')),wan]),E('label',{},[E('span',{},tx('LAN device')),lan]),E('label',{},[E('span',{},tx('LAN address')),ip]),E('label',{'class':'m-check-row'},[iot,E('span',{},tx('Create isolated IoT VLAN 20 (192.168.20.1/24)'))])]),E('div',{'class':'m-inline-actions'},[apply,rollback])]);
 if(st.done){profile.style.display='none';let re=E('button',{'type':'button','class':'m-secondary-button'},tx('Reconfigure Network'));re.addEventListener('click',function(){profile.style.display='block';re.style.display='none';profile.scrollIntoView({behavior:'smooth',block:'start'});});
   return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('Mrouter Setup')),E('div',{'class':'m-subtitle'},tx('Safe first-run setup without silently replacing an existing OpenWrt network'))]),E('span',{'class':'m-state-pill good'},tx('Configured'))]),st.pending?E('div',{'class':'m-info-card m-warning-card'},[E('strong',{},tx('Reboot required')),E('span',{},tx('A saved network profile is waiting for a reboot.'))]):'',E('div',{'class':'m-section m-setup-complete'},[E('span',{'class':'m-setup-check'},tx('✓')),E('div',{},[E('h3',{},tx('Setup complete')),E('p',{'class':'m-muted'},tx(st.mode==='keep'?'Your existing OpenWrt network was preserved. Mrouter did not replace your network, DHCP, firewall or VLAN settings.':'Your Mrouter network profile has been saved.'))]),E('div',{'class':'m-inline-actions'},[E('a',{'class':'m-ios-button m-service-open','href':L.url('admin/dashboard')},tx('Go to Internet Dashboard')),re])]),profile,E('div',{'class':'m-info-card'},[E('strong',{},tx('Advanced hardware')),E('span',{},tx('For DSA switches, bridges or custom VLAN layouts, use Advanced → Networks.'))])]);
 }
 return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('Mrouter Setup')),E('div',{'class':'m-subtitle'},tx('Choose how Mrouter should treat the existing OpenWrt network'))]),E('span',{'class':'m-state-pill neutral'},tx('Not completed'))]),E('div',{'class':'m-section'},[E('h3',{},tx('Keep Existing OpenWrt Configuration')),E('p',{'class':'m-muted'},tx('Recommended when Mrouter is installed on a router that is already configured. Nothing in network, DHCP, firewall or VLAN settings will be changed.')),E('div',{'class':'m-inline-actions'},[keep])]),profile]);
}});
