'use strict';
'require view';
'require fs';
const HELPER='/usr/libexec/mrouter-advanced';
function tx(v){return [String(v==null||v===''?'—':v)];}
function exec(a){return fs.exec(HELPER,a||[]).catch(function(){return{stdout:''};});}
function parse(r){let o={dns:{},dhcp:[],res:[],leases:0};String((r&&r.stdout)||'').split(/\r?\n/).forEach(function(l){let p=l.split('|');if(p[0]==='DNS')o.dns={domain:p[1],local:p[2],noresolv:p[3]==='1',servers:p[4],port:p[5],dnssec:p[6]==='1'};else if(p[0]==='DHCP')o.dhcp.push({id:p[1],iface:p[2],ignore:p[3]==='1',start:p[4],limit:p[5],lease:p[6]});else if(p[0]==='RES')o.res.push({name:p[1],mac:p[2],ip:p[3]});else if(p[0]==='LEASES')o.leases=Number(p[1])||0;});return o;}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,load:function(){return exec(['snapshot']);},render:function(raw){let s=parse(raw),dh=E('div',{'class':'m-modern-grid'});s.dhcp.forEach(function(d){dh.appendChild(E('div',{'class':'m-modern-net-card'},[E('div',{'class':'m-modern-net-head'},[E('span',{'class':'m-modern-icon'},tx('D')),E('div',{},[E('strong',{},tx(d.iface||d.id)),E('span',{},tx('DHCP server'))]),E('span',{'class':'m-state-pill '+(d.ignore?'neutral':'good')},tx(d.ignore?'Off':'On'))]),E('div',{'class':'m-modern-net-grid'},[E('div',{},[E('span',{},tx('Start')),E('strong',{},tx(d.start))]),E('div',{},[E('span',{},tx('Pool size')),E('strong',{},tx(d.limit))]),E('div',{},[E('span',{},tx('Lease time')),E('strong',{},tx(d.lease))])])]))});if(!s.dhcp.length)dh.appendChild(E('div',{'class':'m-empty-card'},tx('No DHCP scopes configured.')));
 let res=E('div',{'class':'m-simple-list'});s.res.slice(0,12).forEach(function(r){res.appendChild(E('div',{'class':'m-simple-row'},[E('div',{},[E('strong',{},tx(r.name||'Reserved device')),E('span',{},tx(r.mac))]),E('code',{},tx(r.ip))]));});if(!s.res.length)res.appendChild(E('div',{'class':'m-empty'},tx('No reserved addresses yet.')));
 let upstream=s.dns.servers||(!s.dns.noresolv?'Automatic from WAN':'Not configured');return E('div',{'class':'mrouter-page'},[
 E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('DHCP & DNS')),E('div',{'class':'m-subtitle'},tx('Addresses, reservations and name resolution without the dnsmasq jargon'))]),E('a',{'class':'m-secondary-link-button','href':L.url('admin/advanced/expert/dhcp')},tx('Expert DNS Settings'))]),
 E('div',{'class':'m-stats-grid'},[E('div',{'class':'m-stat-card'},[E('span',{},tx('Active leases')),E('strong',{},tx(s.leases))]),E('div',{'class':'m-stat-card'},[E('span',{},tx('Reservations')),E('strong',{},tx(s.res.length))]),E('div',{'class':'m-stat-card'},[E('span',{},tx('Local domain')),E('strong',{},tx(s.dns.domain||'lan'))]),E('div',{'class':'m-stat-card'},[E('span',{},tx('DNS listening port')),E('strong',{},tx(s.dns.port||'53'))])]),
 E('div',{'class':'m-section'},[E('div',{'class':'m-section-header'},[E('div',{},[E('h3',{},tx('DNS Resolver')),E('p',{'class':'m-muted'},tx('Clients ask Mrouter first; Mrouter forwards queries to the selected upstream resolver.'))]),E('a',{'class':'m-secondary-link-button','href':L.url('admin/services/local-services')},tx('DNS Provider'))]),E('div',{'class':'m-health-strip'},[E('div',{},[E('span',{},tx('Upstream')),E('strong',{},tx(upstream))]),E('span',{'class':'m-state-pill '+(upstream==='Not configured'?'bad':'good')},tx(upstream==='Not configured'?'Needs attention':'Configured'))])]),
 E('div',{'class':'m-section'},[E('h3',{},tx('DHCP Networks')),dh]),
 E('div',{'class':'m-section'},[E('div',{'class':'m-section-header'},[E('div',{},[E('h3',{},tx('Reserved Addresses')),E('p',{'class':'m-muted'},tx('Keep important devices on predictable addresses.'))]),E('a',{'class':'m-ios-button m-service-open','href':L.url('admin/advanced/expert/dhcp')},tx('+ Add Reservation'))]),res])
]);}});
