'use strict';
'require view';
'require fs';
'require ui';

const HELPER='/usr/libexec/mrouter-advanced';
function tx(v){return [String(v==null||v===''?'—':v)];}
function exec(a){return fs.exec(HELPER,a||[]).catch(function(e){return{code:1,stdout:'',stderr:String(e)};});}
function resultCard(title){let body=E('div',{'class':'m-diag-result-body'},[E('div',{'class':'m-empty'},tx('Run a test to see the result.'))]);return{root:E('div',{'class':'m-diag-result'},[E('div',{'class':'m-section-header'},[E('h3',{},tx(title)),E('span',{'class':'m-state-pill neutral'},tx('Ready'))]),body]),body:body};}
function setResult(box,title,r){let text=String((r&&r.stdout)||(r&&r.stderr)||'No output').trim();box.body.replaceChildren();let ok=!r.code,status=E('span',{'class':'m-state-pill '+(ok?'good':'bad')},tx(ok?'Success':'Failed'));box.root.querySelector('.m-section-header').lastChild.replaceWith(status);let summary=[];if(title==='Ping'){let loss=text.match(/([0-9.]+)% packet loss/),times=text.match(/=\s*([0-9.]+)\/([0-9.]+)\/([0-9.]+)\//);if(loss)summary.push(['Packet loss',loss[1]+'%']);if(times){summary.push(['Minimum',times[1]+' ms']);summary.push(['Average',times[2]+' ms']);summary.push(['Maximum',times[3]+' ms']);}}
 if(title==='Port Test'&&/^(OPEN|CLOSED)\|/.test(text)){let p=text.split('|');summary.push(['Host',p[1]]);summary.push(['Port',p[2]]);summary.push(['Status',p[0]==='OPEN'?'Open':'Closed']);}
 if(summary.length){let g=E('div',{'class':'m-diag-summary'});summary.forEach(function(x){g.appendChild(E('div',{},[E('span',{},tx(x[0])),E('strong',{},tx(x[1]))]));});box.body.appendChild(g);}if(title==='Self-Test'){let list=E('div',{'class':'m-simple-list'});text.split(/\r?\n/).forEach(function(l){let p=l.split('|');if(p[0]==='CHECK')list.appendChild(E('div',{'class':'m-simple-row'},[E('strong',{},tx(p[1])),E('span',{'class':'m-state-pill '+(p[2]==='PASS'?'good':'bad')},tx(p[2]))]));});box.body.appendChild(list);}else{let details=E('details',{'class':'m-raw-output'},[E('summary',{},tx(summary.length?'Raw output':'Output')),E('pre',{},tx(text))]);box.body.appendChild(details);}}
function tool(title,desc,controls,button,box){return E('div',{'class':'m-diag-tool'},[E('div',{'class':'m-diag-tool-head'},[E('div',{},[E('h3',{},tx(title)),E('p',{},tx(desc))]),button]),E('div',{'class':'m-diag-controls'},controls),box.root]);}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,render:function(){
 let pingHost=E('input',{'class':'m-ios-input','value':'1.1.1.1'}),pingMode=E('select',{'class':'m-ios-input'},[E('option',{'value':'ping'},tx('IPv4')),E('option',{'value':'ping6'},tx('IPv6'))]),pingBox=resultCard('Ping'),pingBtn=E('button',{'class':'m-ios-button','type':'button'},tx('Run Ping'));pingBtn.addEventListener('click',function(){pingBtn.disabled=true;exec(['diagnostic',pingMode.value,pingHost.value.trim()]).then(function(r){setResult(pingBox,'Ping',r);}).finally(function(){pingBtn.disabled=false;});});
 let traceHost=E('input',{'class':'m-ios-input','value':'1.1.1.1'}),traceBox=resultCard('Traceroute'),traceBtn=E('button',{'class':'m-ios-button','type':'button'},tx('Trace Route'));traceBtn.addEventListener('click',function(){traceBtn.disabled=true;exec(['diagnostic','trace',traceHost.value.trim()]).then(function(r){setResult(traceBox,'Traceroute',r);}).finally(function(){traceBtn.disabled=false;});});
 let dnsHost=E('input',{'class':'m-ios-input','value':'openwrt.org'}),dnsServer=E('select',{'class':'m-ios-input'},[E('option',{'value':''},tx('Mrouter / system resolver')),E('option',{'value':'1.1.1.1'},tx('Cloudflare 1.1.1.1')),E('option',{'value':'8.8.8.8'},tx('Google 8.8.8.8'))]),dnsBox=resultCard('DNS Lookup'),dnsBtn=E('button',{'class':'m-ios-button','type':'button'},tx('Lookup'));dnsBtn.addEventListener('click',function(){dnsBtn.disabled=true;exec(['diagnostic','dns',dnsHost.value.trim(),dnsServer.value]).then(function(r){setResult(dnsBox,'DNS Lookup',r);}).finally(function(){dnsBtn.disabled=false;});});
 let portHost=E('input',{'class':'m-ios-input','placeholder':'192.168.11.103','value':''}),port=E('input',{'class':'m-ios-input','type':'number','min':'1','max':'65535','value':'443'}),portBox=resultCard('Port Test'),portBtn=E('button',{'class':'m-ios-button','type':'button'},tx('Test Port'));portBtn.addEventListener('click',function(){if(!portHost.value.trim()){ui.addNotification(null,E('p',{},tx('Enter a host or IP address.')),'warning');return;}portBtn.disabled=true;exec(['diagnostic','port',portHost.value.trim(),String(port.value||'443')]).then(function(r){setResult(portBox,'Port Test',r);}).finally(function(){portBtn.disabled=false;});});
 let selfBox=resultCard('Self-Test'),selfBtn=E('button',{'class':'m-ios-button','type':'button'},tx('Run Self-Test'));selfBtn.addEventListener('click',function(){selfBtn.disabled=true;exec(['diagnostic','selftest']).then(function(r){setResult(selfBox,'Self-Test',r);}).finally(function(){selfBtn.disabled=false;});});
 return E('div',{'class':'mrouter-page'},[
  E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('Diagnostics')),E('div',{'class':'m-subtitle'},tx('Test connectivity and name resolution without memorising network commands'))])]),
  E('div',{'class':'m-section'},[E('div',{'class':'m-section-header'},[E('div',{},[E('h3',{},tx('Mrouter Self-Test')),E('p',{'class':'m-muted'},tx('Checks the default route, gateway, Internet, DNS, time and essential services.'))]),selfBtn]),selfBox.root]),
  E('div',{'class':'m-diag-grid'},[
   tool('Ping','Measure latency and packet loss.',[E('label',{},[E('span',{},tx('Target')),pingHost]),E('label',{},[E('span',{},tx('Protocol')),pingMode])],pingBtn,pingBox),
   tool('Traceroute','See the network hops between Mrouter and a destination.',[E('label',{},[E('span',{},tx('Target')),traceHost])],traceBtn,traceBox),
   tool('DNS Lookup','Ask Mrouter or a public resolver to resolve a hostname.',[E('label',{},[E('span',{},tx('Hostname')),dnsHost]),E('label',{},[E('span',{},tx('Resolver')),dnsServer])],dnsBtn,dnsBox),
   tool('Port / Service Test','Check whether a TCP service is reachable.',[E('label',{},[E('span',{},tx('Host / IP')),portHost]),E('label',{},[E('span',{},tx('TCP port')),port])],portBtn,portBox)
  ])
 ]);
}});
