'use strict';
'require view';
'require fs';
'require ui';
const H='/usr/libexec/mrouter-firewall',A='/usr/libexec/mrouter-advanced';
function t(v){return[String(v==null||v===''?'—':v)];}function run(p,a){return fs.exec(p,a||[]).catch(e=>({code:1,stdout:'',stderr:String(e)}));}
function pf(r){let o={up:false,installed:false,f:[],u:[]};String((r&&r.stdout)||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='STATUS'){o.up=p[1]==='1';o.installed=p[2]==='1';}else if(p[0]==='FORWARD')o.f.push({id:p[1],name:p[2],src:p[3],ext:p[4],dest:p[5],ip:p[6],int:p[7],proto:p[8]});else if(p[0]==='UPNP')o.u.push(p.slice(1).join('|'));});return o;}
function matrix(r){let z=[],f=[];String((r&&r.stdout)||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='ZONE')z.push({name:p[1],input:p[2],output:p[3],forward:p[4],nets:p[5]});if(p[0]==='FWD')f.push(p[1]+'>'+p[2]);});return{z:z,f:f};}
function good(r){if(!r||r.code!==0){ui.addNotification(null,E('p',{},t((r&&(r.stderr||r.stdout))||'Action failed')),'error');return false;}return true;}function tog(on){let b=E('button',{'class':'m-toggle m-toggle-small'+(on?' on':''),'type':'button'},[E('span',{})]);b.onclick=()=>b.classList.toggle('on');return b;}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,load:()=>Promise.all([run(H,['status']),run(A,['snapshot'])]).then(d=>[pf(d[0]),matrix(d[1])]),render(d){let s=d[0],m=d[1],name=E('input',{'class':'m-ios-input','placeholder':'Home Assistant'}),ext=E('input',{'class':'m-ios-input','type':'number','placeholder':'8123'}),ip=E('input',{'class':'m-ios-input','placeholder':'192.168.11.50'}),intr=E('input',{'class':'m-ios-input','type':'number','placeholder':'8123'}),proto=E('select',{'class':'m-ios-input'},[E('option',{'value':'tcp'},t('TCP')),E('option',{'value':'udp'},t('UDP')),E('option',{'value':'tcp udp'},t('TCP + UDP'))]),add=E('button',{'class':'m-primary-button','type':'button'},t('Add Port Forward'));add.onclick=()=>{add.disabled=true;run(H,['add-forward',name.value.trim()||'Port forward',ext.value,ip.value.trim(),intr.value,proto.value]).then(r=>{if(good(r))location.reload();else add.disabled=false;});};
 let forwards=E('div',{'class':'m-simple-list'});s.f.forEach(q=>{let del=E('button',{'class':'m-danger-outline-button','type':'button'},t('Delete'));del.onclick=()=>{del.disabled=true;run(H,['delete-forward',q.id]).then(r=>good(r)&&location.reload());};forwards.appendChild(E('div',{'class':'m-simple-row'},[E('div',{},[E('strong',{},t(q.name||q.ext)),E('span',{},t((q.proto||'')+' '+q.ext+' → '+q.ip+':'+q.int))]),del]));});if(!s.f.length)forwards.appendChild(E('div',{'class':'m-empty'},t('No port forwards configured.')));
 let up=tog(s.up),ups=E('button',{'class':'m-secondary-button','type':'button'},t('Apply UPnP'));if(!s.installed){up.disabled=true;ups.disabled=true;}ups.onclick=()=>{ups.disabled=true;run(H,['upnp',up.classList.contains('on')?'1':'0']).then(r=>{if(good(r))location.reload();else ups.disabled=false;});};
 let zones=E('div',{'class':'m-simple-list'});m.z.forEach(z=>zones.appendChild(E('div',{'class':'m-simple-row'},[E('div',{},[E('strong',{},t(z.name)),E('span',{},t('Networks: '+(z.nets||'—')+' · input '+z.input+' · forward '+z.forward))]),E('span',{'class':'m-state-pill neutral'},t('OpenWrt zone'))])));
 return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},t('Firewall')),E('div',{'class':'m-subtitle'},t('OpenWrt firewall zones, explicit port forwards and optional UPnP'))])]),E('div',{'class':'m-section'},[E('h3',{},t('Firewall Zones')),zones]),E('div',{'class':'m-section'},[E('h3',{},t('Port Forwards')),forwards,E('div',{'class':'m-policy-form-grid'},[name,ext,ip,intr,proto]),add]),E('div',{'class':'m-section'},[E('h3',{},t('UPnP / NAT-PMP')),E('div',{'class':'m-setting-row'},[E('div',{},[E('strong',{},t('Automatic port mappings')),E('span',{},t(s.installed?'miniupnpd is installed':'miniupnpd is not installed'))]),up]),ups,s.u.length?E('pre',{'class':'m-code-output'},t(s.u.join('\n'))):E('div',{'class':'m-muted'},t('No active automatic mappings.'))])]);
}});
