'use strict';
'require view';
'require fs';
'require rpc';
'require ui';
'require poll';
const DATA='/usr/libexec/mrouter-client-data', ACTION='/usr/libexec/mrouter-client-action', INFO='/usr/libexec/mrouter-iot-info';
const callDHCPLeases=rpc.declare({object:'luci-rpc',method:'getDHCPLeases',expect:{'':{}}});
function bounded(p,f,ms){return Promise.race([Promise.resolve(p).catch(function(){return f;}),new Promise(function(r){window.setTimeout(function(){r(f);},ms||4500);})]);}
function exec(path,args,f){return bounded(fs.exec(path,args||[]),f||{code:124,stdout:'',stderr:'Timed out'},4500);}
function tx(v){return [String(v==null||v===''?'—':v)];}
function bytes(v){v=Number(v)||0;if(v>=1073741824)return(v/1073741824).toFixed(2)+' GB';if(v>=1048576)return(v/1048576).toFixed(2)+' MB';if(v>=1024)return(v/1024).toFixed(1)+' KB';return v+' B';}
function rate(v){v=(Number(v)||0)*8;if(v>=1e9)return(v/1e9).toFixed(2)+' Gbps';if(v>=1e6)return(v/1e6).toFixed(2)+' Mbps';if(v>=1e3)return(v/1e3).toFixed(1)+' Kbps';return Math.round(v)+' bps';}
function lease(v){v=Number(v);if(!isFinite(v)||v<0)return'Unlimited';let d=Math.floor(v/86400),h=Math.floor(v%86400/3600),m=Math.floor(v%3600/60);return d?d+'d '+h+'h':h?h+'h '+m+'m':m+'m';}
function parseInfo(r){let p=String((r&&r.stdout)||'').trim().split('|');return{configured:p[1]==='1',ip:p[2]||'',mask:p[3]||'',dev:p[4]||'',vlan:p[5]||'',subnet:p[6]||''};}
function parseAux(raw){let o={neigh:{},bandwidth:{},blocked:{},reserved:{},names:{}};String((raw&&raw.stdout)||'').split(/\r?\n/).forEach(function(l){let p=l.split('|'),m=String(p[1]||'').toUpperCase();if(p[0]==='N'&&p.length>=5)o.neigh[String(p[2]).toUpperCase()]={ip:p[1],state:p[3],dev:p[4]};else if(p[0]==='B'&&p.length>=4)o.bandwidth[m]={rx:Number(p[2])||0,tx:Number(p[3])||0};else if(p[0]==='X'&&p[1])o.blocked[m]=true;else if(p[0]==='R'&&p.length>=3)o.reserved[m]=p[2];else if(p[0]==='H'&&p.length>=3)o.names[m]=p.slice(2).join('|');});return o;}
function toggle(on){return E('button',{'class':'m-toggle m-toggle-small'+(on?' on':''),'type':'button'},[E('span',{})]);}
function inSubnet(ip,info){if(!info.configured||!ip)return false;if(info.subnet&&/\/24$/.test(info.subnet)){let n=info.subnet.split('/')[0].split('.').slice(0,3).join('.')+'.';return ip.indexOf(n)===0;}return info.dev?true:false;}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,previous:{},previousTime:null,
 load:function(){return Promise.all([bounded(callDHCPLeases(),{dhcp_leases:[]},4500),exec(DATA,['snapshot-iot'],{stdout:''}),exec(INFO,['status'],{stdout:'STATUS|0|||||'})]);},
 action:function(a,row,b){let wanted=!b.classList.contains('on');b.disabled=true;return fs.exec(ACTION,[a,row.mac,wanted?'1':'0',row.ip,row.name,'iot']).then(function(r){if(!r||r.code!==0)throw new Error((r&&(r.stderr||r.stdout))||'Action failed');b.classList.toggle('on',wanted);}).catch(function(e){ui.addNotification(null,E('p',{},tx(e.message)),'error');}).finally(function(){b.disabled=false;});},
 rows:function(dhcp,aux,info){if(!info.configured)return{online:[],offline:[]};let p=parseAux(aux),ls=(dhcp.dhcp_leases||[]).filter(function(l){return String(l.interface||'')==='iot'||inSubnet(String(l.ipaddr||''),info);}),by={};ls.forEach(function(l){let m=String(l.macaddr||'').toUpperCase();if(m)by[m]=1;});Object.keys(p.neigh).forEach(function(m){let n=p.neigh[m];if(!by[m]&&inSubnet(n.ip,info))ls.push({hostname:p.names[m]||'Unknown device',ipaddr:n.ip,macaddr:m,expires:-1});});let now=Date.now(),dt=this.previousTime?Math.max((now-this.previousTime)/1000,.1):null,cur={},on=[],off=[];ls.forEach(L.bind(function(l){let m=String(l.macaddr||'').toUpperCase();if(!m)return;let n=p.neigh[m],bw=p.bandwidth[m]||{rx:0,tx:0},pr=this.previous[m],dn=0,up=0;if(pr&&dt){dn=Math.max(0,(bw.rx-pr.rx)/dt);up=Math.max(0,(bw.tx-pr.tx)/dt);}cur[m]={rx:bw.rx,tx:bw.tx};let connected=!!n&&!/^(FAILED|INCOMPLETE)$/i.test(n.state||'');let name=(l.hostname&&l.hostname!=='*'?l.hostname:'')||p.names[m]||'Unknown device';let row={name:name,ip:l.ipaddr||(n&&n.ip)||'—',mac:m,lease:lease(l.expires),down:rate(dn),up:rate(up),rx:bytes(bw.rx),tx:bytes(bw.tx),blocked:!!p.blocked[m],reserved:!!p.reserved[m]};(connected?on:off).push(row);},this));this.previous=cur;this.previousTime=now;return{online:on,offline:off};},
 table:function(rows,online){if(!rows.length)return E('div',{'class':'m-empty'},tx(online?'No IoT clients are currently connected.':'No disconnected IoT clients have an active DHCP lease.'));return E('div',{'class':'m-table-scroll'},[E('table',{'class':'m-client-table'},[E('thead',{},[E('tr',{},['Name','IP + MAC','Speed','Traffic','Lease','Reserved IP','Block'].map(function(x){return E('th',{},tx(x));}))]),E('tbody',{},rows.map(L.bind(function(r){let rs=toggle(r.reserved),bl=toggle(r.blocked);rs.addEventListener('click',L.bind(this.action,this,'reserve',r,rs));bl.addEventListener('click',L.bind(this.action,this,'block',r,bl));return E('tr',{},[E('td',{},[E('div',{'class':'m-client-name'},tx(r.name)),E('div',{'class':online?'m-online-small':'m-offline-small'},tx(online?'Online':'Offline'))]),E('td',{},[E('div',{'class':'m-client-ip'},tx(r.ip)),E('div',{'class':'m-client-mac'},tx(r.mac))]),E('td',{'class':'m-speed-cell'},[E('div',{},tx('↓ '+r.down)),E('div',{},tx('↑ '+r.up))]),E('td',{'class':'m-traffic-cell'},[E('div',{},tx('↓ '+r.rx)),E('div',{},tx('↑ '+r.tx))]),E('td',{},tx(r.lease)),E('td',{},rs),E('td',{},bl)]);},this)))])]);},
 render:function(data){let info=parseInfo(data[2]);if(!info.configured)return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('IoT Clients')),E('div',{'class':'m-subtitle'},tx('Isolated devices on the Mrouter-OS IoT network'))]),E('span',{'class':'m-state-pill neutral'},tx('Not configured'))]),E('div',{'class':'m-section m-empty-state-card'},[E('h3',{},tx('IoT network is not configured')),E('p',{'class':'m-muted'},tx('Mrouter is preserving the existing OpenWrt network. Create an IoT network only when you want a separate VLAN and firewall zone.')),E('a',{'class':'m-ios-button m-service-open','href':L.url('admin/advanced/network-settings/interfaces')},tx('Open Networks'))])]);
 let rows=this.rows(data[0]||{},data[1],info),count=E('div',{'class':'m-count m-count-green'},tx(rows.online.length+' online')),title=E('h3',{},tx('Online IoT Clients ('+rows.online.length+')')),on=E('div',{},[this.table(rows.online,true)]),off=E('div',{},[this.table(rows.offline,false)]);let root=E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('IoT Clients')),E('div',{'class':'m-subtitle'},tx('Isolated devices on the Mrouter-OS IoT network'))]),count]),E('div',{'class':'m-iot-network-card'},[E('div',{},[E('span',{},tx('IOT NETWORK')),E('strong',{},tx(info.subnet))]),E('div',{},[E('span',{},tx('ROUTER')),E('strong',{},tx(info.ip))]),E('div',{},[E('span',{},tx('VLAN')),E('strong',{},tx(info.vlan||'—'))]),E('div',{},[E('span',{},tx('DEVICE')),E('strong',{},tx(info.dev))])]),E('div',{'class':'m-section'},[title,on]),E('div',{'class':'m-section'},[E('h3',{},tx('Disconnected — Active DHCP Leases')),off])]);poll.add(L.bind(function(){return Promise.all([bounded(callDHCPLeases(),{dhcp_leases:[]},4500),exec(DATA,['snapshot-iot'],{stdout:''})]).then(L.bind(function(d){let next=this.rows(d[0]||{},d[1],info);count.textContent=next.online.length+' online';title.textContent='Online IoT Clients ('+next.online.length+')';on.replaceChildren(this.table(next.online,true));off.replaceChildren(this.table(next.offline,false));},this)).catch(function(){});},this),5);return root;}
});
