'use strict';
'require view';
'require fs';
'require rpc';
'require ui';
const H='/usr/libexec/mrouter-policy', C='/usr/libexec/mrouter-client-data';
const leases=rpc.declare({object:'luci-rpc',method:'getDHCPLeases',expect:{'':{}}});
function t(v){return [String(v==null||v===''?'—':v)];}function run(p,a){return fs.exec(p,a||[]).catch(e=>({code:1,stdout:'',stderr:String(e)}));}
function tog(on){let b=E('button',{'class':'m-toggle m-toggle-small'+(on?' on':''),'type':'button'},[E('span',{})]);b.onclick=()=>b.classList.toggle('on');return b;}
function parse(r){let o={enabled:false,running:false,targets:[],groups:[],policies:[],runtime:{}};String(r.stdout||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='STATUS'){o.enabled=p[1]==='1';o.running=p[2]==='1';}else if(p[0]==='TARGET')o.targets.push({id:p[1],label:p[2],up:p[3]==='1'});else if(p[0]==='GROUP')o.groups.push({id:p[1],name:p[2],macs:p[3]||''});else if(p[0]==='POLICY')o.policies.push({id:p[1],name:p[2],iface:p[3],src:p[4],dst:p[5],enabled:p[6]==='1',stype:p[7],sval:p[8],dtype:p[9],dval:p[10],target:p[11],fail:p[12]||'block',fallback:p[13],schedule:p[14]||'always',days:p[15]||'',hours:p[16]||'00:00-23:59'});else if(p[0]==='RUNTIME')o.runtime[p[1]]={state:p[2],target:p[3]};});return o;}
function clients(d,r){let m={};(d.dhcp_leases||[]).forEach(x=>{let mac=String(x.macaddr||'').toUpperCase();if(mac)m[mac]={mac:mac,ip:x.ipaddr||'',name:x.hostname&&x.hostname!=='*'?x.hostname:(x.ipaddr||'Unknown')};});String(r.stdout||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='N'){let mac=String(p[2]||'').toUpperCase();if(!m[mac])m[mac]={mac:mac,ip:p[1]||'',name:'Unknown device'};}else if(p[0]==='H'){let mac=String(p[1]||'').toUpperCase();if(m[mac]&&(!m[mac].name||m[mac].name==='Unknown device'))m[mac].name=p.slice(2).join('|');}});return Object.values(m).sort((a,b)=>a.name.localeCompare(b.name));}
function selectTargets(a){return E('select',{'class':'m-ios-input'},a.map(x=>E('option',{'value':x.id},t(x.label+(x.up?'':' — offline')))));}
function humanState(s){return({active:'Active',scheduled:'Outside schedule',wan_fallback:'WAN fallback',vpn_fallback:'VPN fallback',blocked:'Blocked — VPN unavailable',disabled:'Disabled'})[s]||s||'Configured';}
function failText(v){return v==='wan'?'WAN fallback':v==='other'?'Try another VPN':'Block on failure';}
const COUNTRIES=[['gb','United Kingdom'],['us','United States'],['de','Germany'],['fr','France'],['nl','Netherlands'],['ch','Switzerland'],['ro','Romania'],['es','Spain'],['it','Italy'],['at','Austria'],['be','Belgium'],['bg','Bulgaria'],['hr','Croatia'],['cy','Cyprus'],['cz','Czechia'],['dk','Denmark'],['ee','Estonia'],['fi','Finland'],['gr','Greece'],['hu','Hungary'],['ie','Ireland'],['lv','Latvia'],['lt','Lithuania'],['lu','Luxembourg'],['mt','Malta'],['no','Norway'],['pl','Poland'],['pt','Portugal'],['sk','Slovakia'],['si','Slovenia'],['se','Sweden'],['ca','Canada'],['mx','Mexico'],['br','Brazil'],['ar','Argentina'],['au','Australia'],['nz','New Zealand'],['jp','Japan'],['kr','South Korea'],['sg','Singapore'],['hk','Hong Kong'],['in','India'],['ae','UAE'],['il','Israel'],['za','South Africa']];
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,
 load(){return Promise.all([run('/usr/libexec/mrouter-status-policy',[]),leases().catch(()=>({dhcp_leases:[]})),run(C,['snapshot'])]);},
 render(data){let st=parse(data[0]),cl=clients(data[1]||{},data[2]),selected=new Set(),groupSel=new Set(),svc=tog(st.enabled);svc.onclick=()=>{let on=!svc.classList.contains('on');svc.disabled=true;run(H,['service',on?'1':'0']).then(()=>location.reload());};
  let name=E('input',{'class':'m-ios-input','placeholder':'e.g. Streaming TVs'}),stype=E('select',{'class':'m-ios-input'},[['devices','Selected devices'],['group','Device group'],['iot','IoT Network'],['wgremote','WireGuard remote users'],['tailscale','Tailscale remote users'],['subnet','IP / subnet'],['all','Everyone']].map(x=>E('option',{'value':x[0]},t(x[1])))),group=E('select',{'class':'m-ios-input'},[E('option',{'value':''},t('Select group'))]),subnet=E('input',{'class':'m-ios-input','placeholder':'192.168.50.0/24'}),search=E('input',{'class':'m-ios-input','placeholder':'Search devices…'}),chips=E('div',{'class':'m-client-selector'});
  st.groups.forEach(g=>group.appendChild(E('option',{'value':g.id},t(g.name))));function drawClients(){let q=search.value.toLowerCase();chips.replaceChildren.apply(chips,cl.filter(c=>!q||[c.name,c.ip,c.mac].join(' ').toLowerCase().includes(q)).map(c=>{let b=E('button',{'class':'m-client-chip'+(selected.has(c.mac)?' selected':''),'type':'button'},[E('strong',{},t(c.name)),E('span',{},t(c.ip+' • '+c.mac))]);b.onclick=()=>{selected.has(c.mac)?selected.delete(c.mac):selected.add(c.mac);drawClients();};return b;}));}search.oninput=drawClients;drawClients();
  let dtype=E('select',{'class':'m-ios-input'},[['all','Everywhere'],['custom','Websites / IPs'],['service','Service preset'],['country','Country / region'],['subscription','Subscription URL'],['exclude','Everything except…']].map(x=>E('option',{'value':x[0]},t(x[1])))),dest=E('textarea',{'class':'m-policy-destination','placeholder':'netflix.com\n1.1.1.1\n203.0.113.0/24'}),service=E('select',{'class':'m-ios-input'},['netflix','bbc','itv','disney','prime','youtube','teams','zoom','discord'].map(x=>E('option',{'value':x},t(x)))),country=E('select',{'class':'m-ios-input'},COUNTRIES.map(x=>E('option',{'value':x[0]},t(x[1])))),sub=E('input',{'class':'m-ios-input','placeholder':'https://example.com/list.txt'}),via=selectTargets(st.targets),fail=E('select',{'class':'m-ios-input'},[['block','Block traffic'],['wan','Fall back to WAN'],['other','Try another VPN']].map(x=>E('option',{'value':x[0]},t(x[1])))),fallback=selectTargets(st.targets),schedule=E('select',{'class':'m-ios-input'},[['always','Always'],['weekdays','Weekdays'],['weekends','Weekends'],['custom','Custom days']].map(x=>E('option',{'value':x[0]},t(x[1])))),start=E('input',{'class':'m-ios-input','type':'time','value':'00:00'}),end=E('input',{'class':'m-ios-input','type':'time','value':'23:59'}),daysSet=new Set([1,2,3,4,5]),dayBox=E('div',{'class':'m-inline-actions'});
  ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach((d,i)=>{let b=E('button',{'class':'m-secondary-button'+(daysSet.has(i+1)?' selected':''),'type':'button'},t(d));b.onclick=()=>{daysSet.has(i+1)?daysSet.delete(i+1):daysSet.add(i+1);b.classList.toggle('selected',daysSet.has(i+1));};dayBox.appendChild(b);});
  function vis(){chips.style.display=search.style.display=stype.value==='devices'?'':'none';group.style.display=stype.value==='group'?'':'none';subnet.style.display=stype.value==='subnet'?'':'none';dest.style.display=['custom','exclude'].includes(dtype.value)?'':'none';service.style.display=dtype.value==='service'?'':'none';country.style.display=dtype.value==='country'?'':'none';sub.style.display=dtype.value==='subscription'?'':'none';fallback.style.display=fail.value==='other'?'':'none';let timed=schedule.value!=='always';start.style.display=end.style.display=timed?'':'none';dayBox.style.display=schedule.value==='custom'?'':'none';}stype.onchange=dtype.onchange=fail.onchange=schedule.onchange=vis;vis();
  let preview=E('div',{'class':'m-info-banner'});function ptext(){let src=stype.value==='devices'?(selected.size?selected.size+' selected device(s)':'No devices selected'):stype.options[stype.selectedIndex].text,dt=dtype.options[dtype.selectedIndex].text,tr=via.options[via.selectedIndex]?via.options[via.selectedIndex].text:'No target';preview.textContent=src+' → '+dt+' → '+tr+' → '+failText(fail.value);} [stype,dtype,via,fail].forEach(x=>x.onchange=(()=>{let old=x.onchange;return()=>{if(old)old();ptext();};})());ptext();
  let add=E('button',{'class':'m-primary-button'},t('Add Policy'));add.onclick=()=>{let sv=stype.value==='devices'?Array.from(selected).join(','):stype.value==='group'?group.value:stype.value==='subnet'?subnet.value.trim():'',dv=dtype.value==='custom'||dtype.value==='exclude'?dest.value.trim():dtype.value==='service'?service.value:dtype.value==='country'?country.value:dtype.value==='subscription'?sub.value.trim():'';if(!name.value.trim())return ui.addNotification(null,E('p',{},t('Policy name is required.')),'warning');add.disabled=true;run(H,['add',name.value.trim(),stype.value,sv,dtype.value,dv,via.value,fail.value,fallback.value,schedule.value,Array.from(daysSet).sort().join(','),start.value,end.value]).then(r=>{if(r.code)ui.addNotification(null,E('p',{},t(r.stderr||r.stdout||'Unable to add policy')),'error');else location.reload();}).finally(()=>add.disabled=false);};
  let plist=E('div',{'class':'m-simple-list'});st.policies.forEach((p,i)=>{let rt=st.runtime[p.id]||{},en=tog(p.enabled);en.onclick=()=>{en.disabled=true;run(H,['toggle',p.id,p.enabled?'0':'1']).then(()=>location.reload());};let up=E('button',{'class':'m-secondary-button'},t('↑')),down=E('button',{'class':'m-secondary-button'},t('↓')),del=E('button',{'class':'m-danger-outline-button'},t('Delete'));up.disabled=i===0;down.disabled=i===st.policies.length-1;up.onclick=()=>run(H,['move',p.id,'up']).then(()=>location.reload());down.onclick=()=>run(H,['move',p.id,'down']).then(()=>location.reload());del.onclick=()=>{if(confirm('Delete policy "'+p.name+'"?'))run(H,['delete',p.id]).then(()=>location.reload());};plist.appendChild(E('div',{'class':'m-modern-net-card'},[E('div',{'class':'m-modern-net-head'},[E('div',{},[E('strong',{},t((i+1)+'. '+p.name)),E('span',{},t((p.sval||p.src||'Any')+' → '+(p.dval||p.dst||'Everywhere')+' → '+(rt.target||p.target||p.iface)))]),E('span',{'class':'m-state-pill '+(rt.state==='blocked'?'bad':rt.state==='active'?'good':rt.state&&rt.state!=='disabled'?'warn':'neutral')},t(humanState(rt.state)))]),E('div',{'class':'m-muted'},t(failText(p.fail)+' · '+(p.schedule==='always'?'Always':p.schedule+' '+p.hours))),E('div',{'class':'m-inline-actions'},[en,up,down,del])]))});if(!st.policies.length)plist.appendChild(E('div',{'class':'m-empty'},t('No policies configured.')));
  let gname=E('input',{'class':'m-ios-input','placeholder':'Group name'}),gchips=E('div',{'class':'m-client-selector'});cl.forEach(c=>{let b=E('button',{'class':'m-client-chip','type':'button'},[E('strong',{},t(c.name)),E('span',{},t(c.mac))]);b.onclick=()=>{groupSel.has(c.mac)?groupSel.delete(c.mac):groupSel.add(c.mac);b.classList.toggle('selected',groupSel.has(c.mac));};gchips.appendChild(b);});let gadd=E('button',{'class':'m-secondary-button'},t('Create Group'));gadd.onclick=()=>{if(!gname.value.trim()||!groupSel.size)return;gadd.disabled=true;run(H,['group-add',gname.value.trim(),Array.from(groupSel).join(',')]).then(r=>r.code?ui.addNotification(null,E('p',{},t(r.stderr||'Unable to create group')),'error'):location.reload()).finally(()=>gadd.disabled=false);};let gl=E('div',{'class':'m-simple-list'});st.groups.forEach(g=>{let d=E('button',{'class':'m-danger-outline-button'},t('Delete'));d.onclick=()=>run(H,['group-delete',g.id]).then(()=>location.reload());gl.appendChild(E('div',{'class':'m-simple-row'},[E('div',{},[E('strong',{},t(g.name)),E('span',{},t(g.macs))]),d]));});
  return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},t('Policy Routing')),E('div',{'class':'m-subtitle'},t('FROM → TO → VIA → IF VPN FAILS'))]),E('label',{'class':'m-inline-toggle-label'},[E('span',{},t(st.running?'Running':st.enabled?'Enabled':'Disabled')),svc])]),E('div',{'class':'m-section'},[E('h3',{},t('Create Policy')),preview,E('div',{'class':'m-policy-step-grid'},[E('div',{'class':'m-policy-step'},[E('strong',{},t('1 · FROM')),stype,search,chips,group,subnet]),E('div',{'class':'m-policy-step'},[E('strong',{},t('2 · TO')),dtype,dest,service,country,sub]),E('div',{'class':'m-policy-step'},[E('strong',{},t('3 · VIA')),via]),E('div',{'class':'m-policy-step'},[E('strong',{},t('4 · IF VPN FAILS')),fail,fallback])]),E('div',{'class':'m-policy-form-grid'},[E('label',{},[E('span',{},t('Policy name')),name]),E('label',{},[E('span',{},t('Schedule')),schedule]),start,end]),dayBox,add]),E('div',{'class':'m-section'},[E('h3',{},t('Policies — first match wins')),plist]),E('div',{'class':'m-section'},[E('h3',{},t('Device Groups')),gname,gchips,gadd,gl])]);
 }
});
