'use strict';
'require view';
'require fs';
'require ui';

const HELPER='/usr/libexec/mrouter-advanced';
function tx(v){return [String(v==null||v===''?'—':v)];}
function exec(a){return fs.exec(HELPER,a||[]).catch(function(e){return{code:1,stdout:'',stderr:String(e)};});}
function parse(r){let o={sqm:null,nets:[]};String((r&&r.stdout)||'').split(/\r?\n/).forEach(function(l){let p=l.split('|');if(p[0]==='SQM'&&!o.sqm)o.sqm={id:p[1],enabled:p[2]==='1',iface:p[3],down:p[4],up:p[5],qdisc:p[6],script:p[7]};else if(p[0]==='NET')o.nets.push({name:p[1],dev:p[3]});});return o;}
function toggle(on){return E('button',{'class':'m-toggle m-toggle-large'+(on?' on':''),'type':'button'},[E('span',{})]);}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,load:function(){return exec(['snapshot']);},render:function(raw){let s=parse(raw),q=s.sqm||{enabled:false,iface:'',down:'',up:'',qdisc:'cake',script:'piece_of_cake.qos'};let wan=s.nets.find(function(n){return n.name==='wan';});let enabled=toggle(q.enabled);enabled.addEventListener('click',function(){enabled.classList.toggle('on');});
 let iface=E('select',{'class':'m-ios-input'});let devs={};s.nets.forEach(function(n){if(n.dev&&!devs[n.dev]){devs[n.dev]=1;iface.appendChild(E('option',{'value':n.dev},tx(n.dev+(n.name?' · '+n.name:''))));}});if(q.iface)iface.value=q.iface;else if(wan&&wan.dev)iface.value=wan.dev;
 let down=E('input',{'class':'m-ios-input','type':'number','min':'0','value':q.down||'0'}),up=E('input',{'class':'m-ios-input','type':'number','min':'0','value':q.up||'0'}),profile=E('select',{'class':'m-ios-input'},[E('option',{'value':'balanced'},tx('Balanced')),E('option',{'value':'gaming'},tx('Gaming & Calls')),E('option',{'value':'streaming'},tx('Streaming')),E('option',{'value':'custom'},tx('Custom'))]);
 let save=E('button',{'class':'m-ios-button','type':'button'},tx('Apply Traffic Control'));save.addEventListener('click',function(){save.disabled=true;exec(['sqm-save',enabled.classList.contains('on')?'1':'0',iface.value,String(down.value||'0'),String(up.value||'0'),profile.value]).then(function(r){if(r.code){save.disabled=false;ui.addNotification(null,E('p',{},tx(r.stderr||'Could not apply SQM.')),'error');}else{ui.addNotification(null,E('p',{},tx('Traffic Control settings applied.')),'info');window.setTimeout(function(){window.location.reload();},700);}});});
 return E('div',{'class':'mrouter-page'},[
 E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},tx('Traffic Control')),E('div',{'class':'m-subtitle'},tx('Keep calls, games and streaming responsive when the connection is busy'))]),E('span',{'class':'m-state-pill '+(q.enabled?'good':'neutral')},tx(q.enabled?'Smart Queue On':'Off'))]),
 E('div',{'class':'m-hero-card m-qos-hero'},[E('div',{},[E('h3',{},tx('Smart Queue')),E('p',{},tx('Mrouter uses CAKE underneath. Set your real Internet speeds and let the router control queueing automatically.'))]),E('div',{'class':'m-app-control-row'},[E('span',{},tx('Enable')),enabled])]),
 E('div',{'class':'m-section'},[E('h3',{},tx('Internet Capacity')),E('p',{'class':'m-muted'},tx('For best results, enter about 90–95% of the speed you consistently receive from your ISP. Values are in kbit/s.')),E('div',{'class':'m-service-form'},[E('label',{},[E('span',{},tx('Internet interface')),iface]),E('label',{},[E('span',{},tx('Profile')),profile]),E('label',{},[E('span',{},tx('Download kbit/s')),down]),E('label',{},[E('span',{},tx('Upload kbit/s')),up])]),E('div',{'class':'m-inline-actions'},[save])]),
 E('div',{'class':'m-section'},[E('h3',{},tx('What the profiles mean')),E('div',{'class':'m-qos-presets'},[E('div',{},[E('strong',{},tx('Balanced')),E('span',{},tx('Best default for most homes.'))]),E('div',{},[E('strong',{},tx('Gaming & Calls')),E('span',{},tx('Use when low latency matters more than bulk throughput.'))]),E('div',{},[E('strong',{},tx('Streaming')),E('span',{},tx('Good for households with several TVs and downloads.'))]),E('div',{},[E('strong',{},tx('Custom')),E('span',{},tx('Keeps the simple Mrouter form while advanced CAKE settings stay available below.'))])])]),
 E('div',{'class':'m-info-card'},[E('strong',{},tx('Advanced queue settings')),E('span',{},[document.createTextNode('CAKE/FQ-CoDel scripts, link-layer overhead and unusual WAN types remain available in '),E('a',{'href':L.url('admin/advanced/expert/sqm')},tx('Expert SQM')),document.createTextNode('.')])])
]);}});
