'use strict';
'require view';
'require fs';
'require ui';
const SERVER='/usr/libexec/mrouter-wireguard', SSTAT='/usr/libexec/mrouter-status-wireguard', CLIENT='/usr/libexec/mrouter-wireguard-client', CSTAT='/usr/libexec/mrouter-status-wireguard-client', UPLOAD='/tmp/mrouter-wireguard-client-upload';
function t(v){return [String(v==null||v===''?'—':v)];} function run(p,a){return fs.exec(p,a||[]).catch(e=>({code:1,stdout:'',stderr:String(e)}));}
function ps(r){let o={configured:false,running:false,address:'10.14.0.1/24',port:'51820',publicIP:'',clients:[]};String(r.stdout||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='STATUS'){o.configured=p[1]==='1';o.running=p[2]==='1';o.port=p[4]||'51820';o.address=p[5]||o.address;o.publicIP=p[6]||'';}else if(p[0]==='CLIENT')o.clients.push({id:p[1],name:p.slice(2).join('|')});});return o;}
function pc(r){let o=[];String(r.stdout||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='PROFILE')o.push({id:p[1],name:p[2],iface:p[3],enabled:p[4]==='1',up:p[5]==='1',healthy:p[6]==='1',age:+p[7]||0,endpoint:p[8],address:p[9],dns:p[10],rx:+p[11]||0,tx:+p[12]||0,full:p[13]==='1'});});return o;}
function cfg(r){let s=String(r.stdout||''),a=s.indexOf('CONFIG_BEGIN\n'),b=s.indexOf('\nCONFIG_END');return a>=0&&b>a?s.substring(a+13,b):'';}
function bytes(v){v=+v||0;if(v>=1073741824)return(v/1073741824).toFixed(2)+' GB';if(v>=1048576)return(v/1048576).toFixed(1)+' MB';if(v>=1024)return(v/1024).toFixed(1)+' KB';return v+' B';}
function age(v){return !v?'No handshake':v<60?v+' sec ago':v<3600?Math.floor(v/60)+' min ago':Math.floor(v/3600)+' hr ago';}
function notify(r){if(!r||r.code!==0){ui.addNotification(null,E('p',{},t((r&&(r.stderr||r.stdout))||'Action failed')),'error');return false;}return true;}
function toggle(on){let b=E('button',{'class':'m-toggle m-toggle-small'+(on?' on':''),'type':'button'},[E('span',{})]);b.onclick=()=>b.classList.toggle('on');return b;}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,
 load(){return Promise.all([run(SSTAT,[]).then(ps),run(CSTAT,[]).then(pc)]);},
 render(data){let st=data[0],vpns=data[1],endpoint=E('input',{'class':'m-ios-input','value':st.publicIP||'','placeholder':'public IP or hostname'}),name=E('input',{'class':'m-ios-input','placeholder':'e.g. iPhone'}),full=toggle(true),out=E('textarea',{'class':'m-wg-config','readonly':'readonly','placeholder':'Generated remote-access configuration appears here.'});
  let gen=E('button',{'class':'m-primary-button','type':'button'},t(st.configured?'Generate Remote Client':'Create Server + Client'));gen.onclick=()=>{let host=endpoint.value.trim();if(!host)return ui.addNotification(null,E('p',{},t('Enter the public endpoint.')),'warning');gen.disabled=true;run(SERVER,['generate',host,full.classList.contains('on')?'1':'0',name.value.trim()||'Mrouter Client']).then(r=>{if(!notify(r))return;let c=cfg(r);if(!c)throw new Error('Generated configuration was not returned');out.value=c;}).catch(e=>ui.addNotification(null,E('p',{},t(e.message)),'error')).finally(()=>gen.disabled=false);};
  let saved=E('div',{'class':'m-simple-list'});st.clients.forEach(c=>{let view=E('button',{'class':'m-secondary-button'},t('View')),rev=E('button',{'class':'m-danger-outline-button'},t('Revoke'));view.onclick=()=>run(SERVER,['view',c.id]).then(r=>{let x=cfg(r);if(x)out.value=x;else notify(r);});rev.onclick=()=>{if(confirm('Revoke '+c.name+'?'))run(SERVER,['revoke',c.id]).then(r=>notify(r)&&location.reload());};saved.appendChild(E('div',{'class':'m-simple-row'},[E('div',{},[E('strong',{},t(c.name)),E('span',{},t('10.14.0.'+c.id))]),E('div',{'class':'m-inline-actions'},[view,rev])]))});if(!st.clients.length)saved.appendChild(E('div',{'class':'m-empty'},t('No remote-access clients yet.')));
  let vpnlist=E('div',{'class':'m-simple-list'});vpns.forEach(p=>{let con=E('button',{'class':p.enabled?'m-secondary-button':'m-primary-button'},t(p.enabled?'Disconnect':'Connect')),ren=E('button',{'class':'m-secondary-button'},t('Rename')),del=E('button',{'class':'m-danger-outline-button'},t('Delete'));con.onclick=()=>{con.disabled=true;run(CLIENT,[p.enabled?'disconnect':'connect',p.id]).then(r=>notify(r)&&location.reload());};ren.onclick=()=>{let n=prompt('Profile name',p.name);if(n&&n.trim())run(CLIENT,['rename',p.id,n.trim()]).then(r=>notify(r)&&location.reload());};del.onclick=()=>{if(confirm('Delete '+p.name+'?'))run(CLIENT,['delete',p.id]).then(r=>notify(r)&&location.reload());};vpnlist.appendChild(E('div',{'class':'m-modern-net-card'},[E('div',{'class':'m-modern-net-head'},[E('div',{},[E('strong',{},t(p.name)),E('span',{},t(p.iface+(p.full?' · Policy Routing ready':' · split tunnel')))]),E('span',{'class':'m-state-pill '+(p.healthy?'good':p.enabled?'warn':'neutral')},t(p.healthy?'Connected':p.enabled?'Waiting for handshake':'Disconnected'))]),E('div',{'class':'m-modern-net-grid'},[E('div',{},[E('span',{},t('Endpoint')),E('strong',{},t(p.endpoint))]),E('div',{},[E('span',{},t('VPN address')),E('strong',{},t(p.address))]),E('div',{},[E('span',{},t('Handshake')),E('strong',{},t(age(p.age)))]),E('div',{},[E('span',{},t('Traffic')),E('strong',{},t('↓ '+bytes(p.rx)+' ↑ '+bytes(p.tx)))])]),E('div',{'class':'m-inline-actions'},[con,ren,del])]))});if(!vpns.length)vpnlist.appendChild(E('div',{'class':'m-empty'},t('No WireGuard VPN provider profiles imported.')));
  let upload=E('button',{'class':'m-primary-button'},t('Import WireGuard .conf'));upload.onclick=()=>ui.uploadFile(UPLOAD,upload.firstChild,'Standard WireGuard .conf').then(reply=>{upload.disabled=true;return run(CLIENT,['import',reply.name]);}).then(r=>{if(notify(r))location.reload();else upload.disabled=false;}).catch(e=>{upload.disabled=false;ui.addNotification(null,E('p',{},t(e.message)),'error');});
  return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},t('WireGuard')),E('div',{'class':'m-subtitle'},t('Remote access into Mrouter and outbound VPN-provider tunnels'))]),E('span',{'class':'m-status-pill '+(st.running||vpns.some(p=>p.healthy)?'m-status-good':'')},t(st.running||vpns.some(p=>p.healthy)?'Active':'No active tunnel'))]),E('div',{'class':'m-section'},[E('h3',{},t('Remote Access Server')),E('div',{'class':'m-stats-grid'},[E('div',{'class':'m-stat-card'},[E('span',{},t('Server')),E('strong',{},t(st.running?'Running':st.configured?'Configured':'Not configured'))]),E('div',{'class':'m-stat-card'},[E('span',{},t('Address')),E('strong',{},t(st.address))]),E('div',{'class':'m-stat-card'},[E('span',{},t('UDP port')),E('strong',{},t(st.port))])]),E('div',{'class':'m-policy-form-grid'},[E('label',{},[E('span',{},t('Client name')),name]),E('label',{},[E('span',{},t('Public endpoint')),endpoint]),E('label',{'class':'m-inline-toggle-label'},[E('span',{},t('Full tunnel')),full])]),gen,out,saved]),E('div',{'class':'m-section'},[E('div',{'class':'m-section-header'},[E('div',{},[E('h3',{},t('VPN Clients')),E('p',{'class':'m-muted'},t('Imported profiles never replace the normal WAN route; Policy Routing chooses who uses them.'))]),upload]),vpnlist])]);
 }
});
