'use strict';
'require view';
'require fs';
'require ui';
const H='/usr/libexec/mrouter-wireless';function t(v){return[String(v==null||v===''?'—':v)];}function run(a){return fs.exec(H,a||[]).catch(e=>({code:1,stdout:'',stderr:String(e)}));}
function parse(r){let o={r:[],s:[]};String(r.stdout||'').split(/\r?\n/).forEach(l=>{let p=l.split('|');if(p[0]==='RADIO')o.r.push({id:p[1],on:p[2]==='1',band:p[3],ch:p[4],mode:p[5],country:p[6],tx:p[7],type:p[8]});else if(p[0]==='SSID')o.s.push({id:p[1],dev:p[2],net:p[3],ssid:p[4],enc:p[5],on:p[6]==='1',mode:p[7]});});return o;}
function notify(r){if(!r||r.code!==0){ui.addNotification(null,E('p',{},t((r&&(r.stderr||r.stdout))||'Action failed')),'error');return false;}return true;}function tog(on){let b=E('button',{'class':'m-toggle m-toggle-small'+(on?' on':''),'type':'button'},[E('span',{})]);b.onclick=()=>b.classList.toggle('on');return b;}
function encsel(v){let s=E('select',{'class':'m-ios-input'},[['sae-mixed','WPA2/WPA3'],['sae','WPA3'],['psk2','WPA2'],['psk-mixed','WPA/WPA2'],['none','Open']].map(x=>E('option',{'value':x[0]},t(x[1]))));s.value=v||'sae-mixed';return s;}
return view.extend({handleSaveApply:null,handleSave:null,handleReset:null,load:()=>run(['status']).then(parse),render(st){let radios=E('div',{'class':'m-modern-grid'});st.r.forEach(r=>{let on=tog(r.on),ch=E('input',{'class':'m-ios-input','value':r.ch||'auto'}),mode=E('input',{'class':'m-ios-input','value':r.mode||''}),country=E('input',{'class':'m-ios-input','value':r.country||''}),tx=E('input',{'class':'m-ios-input','type':'number','placeholder':'TX power','value':r.tx||''}),save=E('button',{'class':'m-secondary-button'},t('Apply Radio'));save.onclick=()=>{save.disabled=true;run(['radio-save',r.id,on.classList.contains('on')?'1':'0',ch.value.trim(),mode.value.trim(),country.value.trim(),tx.value.trim()]).then(x=>notify(x)&&location.reload()).finally(()=>save.disabled=false);};radios.appendChild(E('div',{'class':'m-modern-net-card'},[E('div',{'class':'m-modern-net-head'},[E('div',{},[E('strong',{},t(r.id)),E('span',{},t((r.band||'Wireless')+' · '+(r.type||'radio')))]),on]),E('div',{'class':'m-policy-form-grid'},[E('label',{},[E('span',{},t('Channel')),ch]),E('label',{},[E('span',{},t('Mode / width')),mode]),E('label',{},[E('span',{},t('Country')),country]),E('label',{},[E('span',{},t('TX power')),tx])]),save]));});if(!st.r.length)radios.appendChild(E('div',{'class':'m-empty-card'},t('No wireless radios configured. This is normal on wired x86 appliances.')));
 let list=E('div',{'class':'m-simple-list'});st.s.forEach(s=>{let edit=E('button',{'class':'m-secondary-button'},t('Edit')),del=E('button',{'class':'m-danger-outline-button'},t('Delete'));edit.onclick=()=>{let ss=prompt('SSID',s.ssid);if(ss===null)return;let key=prompt('New password (leave blank to keep current; ignored for open networks)','');if(key===null)return;let net=prompt('Network',s.net||'lan');if(net===null)return;run(['ssid-save',s.id,s.on?'1':'0',ss.trim(),s.enc||'sae-mixed',key,net.trim()]).then(x=>notify(x)&&location.reload());};del.onclick=()=>{if(confirm('Delete '+s.ssid+'?'))run(['delete-ssid',s.id]).then(x=>notify(x)&&location.reload());};list.appendChild(E('div',{'class':'m-simple-row'},[E('div',{},[E('strong',{},t(s.ssid)),E('span',{},t(s.dev+' · '+s.net+' · '+s.enc))]),E('div',{'class':'m-inline-actions'},[E('span',{'class':'m-state-pill '+(s.on?'good':'neutral')},t(s.on?'On':'Off')),edit,del])]))});if(!st.s.length)list.appendChild(E('div',{'class':'m-empty'},t('No Wi-Fi networks configured.')));
 let dev=E('select',{'class':'m-ios-input'},st.r.map(r=>E('option',{'value':r.id},t(r.id+' · '+(r.band||'radio'))))),net=E('input',{'class':'m-ios-input','value':'lan','placeholder':'lan / guest / iot'}),ssid=E('input',{'class':'m-ios-input','placeholder':'Wi-Fi name'}),enc=encsel('sae-mixed'),key=E('input',{'class':'m-ios-input','type':'password','placeholder':'Password'}),add=E('button',{'class':'m-primary-button'},t('Add SSID'));add.disabled=!st.r.length;add.onclick=()=>{add.disabled=true;run(['add-ssid',dev.value,net.value.trim(),ssid.value.trim(),enc.value,key.value]).then(x=>{if(notify(x))location.reload();else add.disabled=false;});};
 return E('div',{'class':'mrouter-page'},[E('div',{'class':'m-page-title'},[E('div',{},[E('h2',{},t('Wireless')),E('div',{'class':'m-subtitle'},t('OpenWrt radio and SSID management; only shown capabilities are applied'))])]),E('div',{'class':'m-section'},[E('h3',{},t('Radios')),radios]),E('div',{'class':'m-section'},[E('h3',{},t('Wi-Fi Networks')),list]),E('div',{'class':'m-section'},[E('h3',{},t('Add Wi-Fi Network')),E('div',{'class':'m-policy-form-grid'},[dev,net,ssid,enc,key]),add,E('div',{'class':'m-info-banner'},t('For Guest or IoT Wi-Fi, create that network first, then bind the SSID to its network name.'))])]);}});
