(function(g){
'use strict';
var BASE='/luci-static/mrouter-ui/pages.json',USER='/luci-static/mrouter-ui/user-pages.json',BRIDGE='/usr/libexec/mrouter-ui-action';
function getJSON(u){return fetch(u,{cache:'no-store'}).then(function(r){return r.ok?r.json():{};}).catch(function(){return{};});}
function merge(a,b){var o={},k;for(k in(a||{}))o[k]=a[k];for(k in(b||{}))o[k]=b[k];return o;}
function E0(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n;}
function exec(fs,spec,args){spec=spec||{};var p=[spec.service||'',spec.action||'status'].concat(args||spec.args||[]);return fs.exec(BRIDGE,p).then(function(r){if(r.code)throw new Error((r.stderr||r.stdout||'Action failed').trim());return(r.stdout||'').trim();});}
function pipeRows(raw){return String(raw||'').split(/\r?\n/).filter(Boolean).map(function(line){var p=line.split('|');return{tag:p.shift()||'',values:p,raw:line};});}
function parse(raw,spec){spec=spec||{};if(spec.parser==='json'){try{return JSON.parse(raw||'{}');}catch(e){return{error:'Invalid JSON',raw:raw};}}if(spec.parser==='pipe'){var rows=pipeRows(raw);if(spec.fields){var r=rows[0]||{values:[]},o={};spec.fields.forEach(function(k,i){o[k]=r.values[i]||'';});o._rows=rows;o.raw=raw;return o;}return{rows:rows,raw:raw};}if(spec.parser==='lines')return{lines:String(raw||'').split(/\r?\n/).filter(Boolean),raw:raw};return{raw:raw};}
function sourceValue(state,ref){if(ref==null)return undefined;var p=String(ref).split('.'),v=state.sources[p.shift()];while(p.length&&v!=null)v=v[p.shift()];return v;}
function interpolate(v,state){return String(v==null?'':v).replace(/\{\{\s*([A-Za-z0-9_.-]+)\s*\}\}/g,function(_,k){var x=sourceValue(state,k);return x==null?'—':String(x);});}
function fieldNode(f,state){var input,val=f.default_from?sourceValue(state,f.default_from):f.default;if(f.type==='select'){input=E0('select','m-ios-input');(f.options||[]).forEach(function(o){var op=E0('option','',typeof o==='object'?o.label:o);op.value=typeof o==='object'?o.value:o;input.appendChild(op);});if(val!=null)input.value=String(val);}else if(f.type==='toggle'){input=E0('input');input.type='checkbox';input.checked=String(val)==='1'||val===true||String(val).toLowerCase()==='true';}else if(f.type==='textarea'||f.type==='yaml'){input=E0('textarea',f.type==='yaml'?'mr-yaml-editor':'m-ios-input');input.rows=f.rows||8;input.value=val==null?'':String(val);}else{input=E0('input','m-ios-input');input.type=f.type==='password'?'password':(f.type==='number'?'number':(f.type==='colour'?'color':'text'));if(val!=null)input.value=String(val);if(f.placeholder)input.placeholder=f.placeholder;}input.dataset.mrField=f.id;if(f.min!=null)input.min=f.min;if(f.max!=null)input.max=f.max;var l=E0('label','mr-schema-field');l.appendChild(E0('span','',f.label||f.id));l.appendChild(input);if(f.help)l.appendChild(E0('small','m-muted',f.help));return l;}
function formValues(node){var o={};node.querySelectorAll('[data-mr-field]').forEach(function(x){o[x.dataset.mrField]=x.type==='checkbox'?(x.checked?'1':'0'):x.value;});return o;}
function resolveArgs(list,vals,state){return(list||[]).map(function(x){var s=String(x),m=s.match(/^\$field\.([A-Za-z0-9_-]+)$/);if(m)return vals[m[1]]==null?'':String(vals[m[1]]);m=s.match(/^\$source\.([A-Za-z0-9_.-]+)$/);if(m){var v=sourceValue(state,m[1]);return v==null?'':String(v);}return s;});}
function notify(ui,msg,type){if(ui&&ui.addNotification)ui.addNotification(null,E0('p','',msg),type||'info');}
function actionButton(a,state,fs,ui,scope){var b=E0('button',a.style==='danger'?'m-danger-outline-button':(a.style==='secondary'?'m-secondary-button':'m-primary-button'),a.label||a.action||'Apply');b.type='button';b.addEventListener('click',function(){if(a.confirm&&!window.confirm(a.confirm===true?'Are you sure?':a.confirm))return;var vals=scope?formValues(scope):{},args=resolveArgs(a.args,vals,state);b.disabled=true;exec(fs,a,args).then(function(out){if(a.success!==false)notify(ui,a.success||'Saved.','info');if(a.reload)setTimeout(function(){location.reload();},120);}).catch(function(e){notify(ui,e.message||'Action failed','error');}).finally(function(){b.disabled=false;});});return b;}
function renderRecords(block,state){var src=state.sources[block.source],sec=E0('div','m-section mr-records');if(block.title)sec.appendChild(E0('h3','',block.title));if(!src){sec.appendChild(E0('div','m-empty','No data.'));return sec;}if(src.error){sec.appendChild(E0('div','m-info-banner',src.error));return sec;}var rows=src.rows||pipeRows(src.raw||'');if(block.tags&&block.tags.length)rows=rows.filter(function(r){return block.tags.indexOf(r.tag)>=0;});if(!rows.length){sec.appendChild(E0('div','m-empty',block.empty||'No data available.'));return sec;}var list=E0('div','mr-record-list');rows.forEach(function(r){var row=E0('div','mr-record-row'),head=E0('div','mr-record-tag',r.tag||'INFO'),vals=E0('div','mr-record-values');r.values.forEach(function(v,i){var lab=(block.columns||[])[i];var cell=E0('div','mr-record-cell');if(lab)cell.appendChild(E0('span','mr-record-label',lab));cell.appendChild(E0('strong','',v===''?'—':v));vals.appendChild(cell);});row.appendChild(head);row.appendChild(vals);list.appendChild(row);});sec.appendChild(list);return sec;}
function renderJSON(block,state){var src=state.sources[block.source],sec=E0('div','m-section mr-json-grid');if(block.title)sec.appendChild(E0('h3','',block.title));if(!src){sec.appendChild(E0('div','m-empty','No data.'));return sec;}if(src.error){sec.appendChild(E0('div','m-info-banner',src.error));return sec;}var keys=block.fields||Object.keys(src).filter(function(k){return k!=='raw'&&k!=='error'&&typeof src[k]!=='object';});var grid=E0('div','m-stats-grid');keys.forEach(function(k){var c=E0('div','m-stat-card');c.appendChild(E0('span','',(block.labels&&block.labels[k])||k.replace(/_/g,' ')));c.appendChild(E0('strong','',src[k]==null||src[k]===''?'—':src[k]));grid.appendChild(c);});sec.appendChild(grid);if(block.array&&Array.isArray(src[block.array])){var list=E0('div','mr-record-list');src[block.array].forEach(function(item){var row=E0('div','mr-record-row'),vals=E0('div','mr-record-values');Object.keys(item).forEach(function(k){var cell=E0('div','mr-record-cell');cell.appendChild(E0('span','mr-record-label',k.replace(/_/g,' ')));cell.appendChild(E0('strong','',item[k]==null||item[k]===''?'—':item[k]));vals.appendChild(cell);});row.appendChild(vals);list.appendChild(row);});sec.appendChild(list);}return sec;}
function renderBlock(block,state,fs,ui){if(block.visible===false)return document.createDocumentFragment();
 if(block.type==='heading')return E0(block.level===2?'h2':'h3','mr-schema-heading',interpolate(block.text||'',state));
 if(block.type==='notice')return E0('div','m-info-banner',interpolate(block.text||'',state));
 if(block.type==='card'){var c=E0('div','m-app-card');if(block.title)c.appendChild(E0('h3','',interpolate(block.title,state)));if(block.text)c.appendChild(E0('p','',interpolate(block.text,state)));return c;}
 if(block.type==='records')return renderRecords(block,state);
 if(block.type==='json')return renderJSON(block,state);
 if(block.type==='code'){var sec0=E0('div','m-section');if(block.title)sec0.appendChild(E0('h3','',block.title));var src0=state.sources[block.source],pre=E0('pre','mr-code');pre.textContent=(src0&&src0.raw)||block.text||'';sec0.appendChild(pre);return sec0;}
 if(block.type==='stats'){var grid=E0('div','m-stats-grid');(block.items||[]).forEach(function(it){var c1=E0('div','m-stat-card'),v=it.value_from?sourceValue(state,it.value_from):interpolate(it.value,state);c1.appendChild(E0('span','',it.label||''));c1.appendChild(E0('strong','',v==null||v===''?'—':v));grid.appendChild(c1);});return grid;}
 if(block.type==='form'){var sec=E0('div','m-section mr-schema-form');if(block.title)sec.appendChild(E0('h3','',block.title));var grid2=E0('div','m-form-grid');(block.fields||[]).forEach(function(f){grid2.appendChild(fieldNode(f,state));});sec.appendChild(grid2);var acts=E0('div','cbi-page-actions');(block.actions||[]).forEach(function(a){acts.appendChild(actionButton(a,state,fs,ui,sec));});sec.appendChild(acts);return sec;}
 if(block.type==='actions'){var sec2=E0('div','m-section');if(block.title)sec2.appendChild(E0('h3','',block.title));var acts2=E0('div','mr-action-row');(block.items||[]).forEach(function(a){acts2.appendChild(actionButton(a,state,fs,ui,null));});sec2.appendChild(acts2);return sec2;}
 if(block.type==='link'){var a0=E0('a','m-secondary-link-button',block.label||'Open');a0.href=block.href||'#';var wrap=E0('div','m-section');if(block.title)wrap.appendChild(E0('h3','',block.title));if(block.text)wrap.appendChild(E0('p','m-muted',block.text));wrap.appendChild(a0);return wrap;}
 return E0('div','m-info-banner','Unsupported YAML block: '+(block.type||'unknown'));}
async function load(pageId,fs){var all=await Promise.all([getJSON(BASE),getJSON(USER)]),base=(all[0].pages||{})[pageId]||{},over=(all[1].pages||{})[pageId]||{},cfg=merge(base,over),state={cfg:cfg,sources:{}};var jobs=[];Object.keys(cfg.sources||{}).forEach(function(id){var spec=cfg.sources[id];jobs.push(exec(fs,spec).then(function(raw){state.sources[id]=parse(raw,spec);}).catch(function(e){state.sources[id]={error:e.message,raw:''};}));});(cfg.layout||[]).forEach(function(b){if(b.source_spec){var id=b.source||b.id||('inline'+jobs.length);jobs.push(exec(fs,b.source_spec).then(function(raw){state.sources[id]=parse(raw,b.source_spec);}).catch(function(e){state.sources[id]={error:e.message,raw:''};}));}});await Promise.all(jobs);return state;}
function render(pageId,state,fs,ui){var cfg=state.cfg||{},root=E0('div','mrouter-page mr-schema-page'),title=E0('div','m-page-title'),box=E0('div');box.appendChild(E0('h2','',cfg.title||pageId));if(cfg.subtitle)box.appendChild(E0('div','m-subtitle',cfg.subtitle));title.appendChild(box);root.appendChild(title);(cfg.layout||[]).forEach(function(b){root.appendChild(renderBlock(b,state,fs,ui));});return root;}
g.MrouterSchemaRuntime={load:load,render:render,exec:exec};
})(window);
